Resources:
  LastTweetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: idName
          AttributeType: S
      KeySchema:
        - AttributeName: idName
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}